name: Test Child
on: 
  workflow_call:
    inputs:
        environment:
          required: true
          type: string
        workspace:
          required: true
          type: string
jobs:
  Job1:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Step 1
        run: |
          echo "${{ secrets.TEST_SECRET }}"
      - name: Step 2
        run: |
          echo "${{ inputs.workspace }}"
      - name: Step 3
        run: |
          echo "${{ vars.WORKSPACE }}"
      - name: Step 4
        run: |
          echo "${GITHUB_REPOSITORY#*/}"
      - name: Step 5
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          ENVIRONMENT=$([ "$GITHUB_REF_NAME" = "main" ] && echo "prd" || echo "dev")
          WORKSPACE="${ENVIRONMENT}_${REPO_NAME}"

          echo "T1_TOKEN=${{ secrets.TOKEN }}" >> $GITHUB_ENV
          echo "T1_TEST=MYTEST" >> $GITHUB_ENV
          echo "T1_WORKSPACE=${WORKSPACE}" >> $GITHUB_ENV

      - name: Step 6
        run: |
          env
